#!/bin/sh /etc/rc.common
# Copyright (C) 2014-2015 Qualcomm Atheros, Inc

#SFE connection manager has a lower priority, it should be started after other connection manager
#to detect the existence of connection manager with higher priority
START=72

have_cm() {
	[ -d "/sys/kernel/debug/ecm" ] && echo 1 && return

	echo 0
}

#load shortcut-fe connection manager
load_sfe_cm() {
	local kernel_version=$(uname -r)

	#shortcut-fe-drv.ko is not needed because other connection manager is not enabled
	[ -d "/sys/module/shortcut_fe_drv" ] && rmmod shortcut_fe_drv

	[ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && {
		[ -d /sys/module/shortcut_fe_cm ] || insmod /lib/modules/$kernel_version/shortcut-fe-cm.ko
	}
	[ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && {
		[ -d /sys/module/fast_classifier ] || insmod /lib/modules/$kernel_version/fast-classifier.ko
	}
}

start() {
	[ "$(have_cm)" = "1" ] || load_sfe_cm
}

stop() {
	[ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
	[ -d /sys/module/fast_classifier ] && rmmod fast_classifier
}
